### PR TITLE
Edits for brevity, VDR as an example of incremental information

### PR DESCRIPTION
**Pull request by SteveLasker**
- A few edits for brevity and conciseness
- Differentiate the VDR as incremental information, where the SBOM is static at the time of initial distribution
Signed-off-by: Steve Lasker <stevenlasker@hotmail.com>

### CODE REVIEW

**Comment by rjb4standards** [comment]
A VDR is a living document that can be linked to an SBOM document directly, see SPDX V2.3 K.1.9; 
https://spdx.github.io/spdx-spec/v2.3/how-to-use/#k19-linking-to-an-sbom-vulnerability-report-for-a-software-product-per-nist-executive-order-14028

**Comment by henkbirkholz** [comment]
> A VDR is a living document that can be linked to an SBOM document directly, see SPDX V2.3 K.1.9; https://spdx.github.io/spdx-spec/v2.3/how-to-use/#k19-linking-to-an-sbom-vulnerability-report-for-a-software-product-per-nist-executive-order-14028

Is there a proposed change associated with this comment?

**Comment by henkbirkholz** [comment]
Feels like an agreement to the "Differentiate the VDR as incremental information, where the SBOM is static at the time of initial distribution" above?

**Comment by SteveLasker** [comment]
Thanks @rjb4standards,
I'd suggest the thing we want to capture with SCITT is the continual evolution of information. It's not ok to just update a document as there's no way to know what the state of the document was at a previous date.

Example:
1. Jan 1, 2022 - the `net-monitor:v1` software was deployed and the VDR showed (all is good). A SCITT claim was submitted, attesting to that current state
1. Jan 10, 2022, the `net-monitor:v1` software was deployed, as there were no known issues. A SCITT claim
1. On March 1, 2022 a new vulnerability was discovered that applied to the previous released and deployed software

On March 2, 2022, a security auditor might ask: "Why did you deploy the net-monitor:v1` software when there's clearly a security problem?
The system has the VDR report from Jan 10, when the software was deployed, to indicate no known vulnerabilities were known at that point. 

SCITT and the underlying evidence store will need to provide the most recent version of an artifactType, with the ability to query the history as well.

Does this give you what you're looking for?

**Comment by rjb4standards** [comment]
Steve, each new VDR will have a different hash value, so any/all of the VDR artifacts can be checked for trustworthiness, but the "most current VDR should always be registered in SCITT, IMO.

**Comment by rjb4standards** [comment]
No additional changes are needed, just replace VEX with VDR and we're good to go.

**Review by OR13 — APPROVED** [review]

**Review by henkbirkholz — APPROVED** [review]

**Pull request merged**
